#!/bin/sh
pushd ${WORKSPACE}
sudo docker build -t ovs .
CID=`sudo docker run -d ovs true`
sudo docker cp $CID:/rpmbuild/RPMS .
sudo chmod -R a+w RPMS
mv RPMS/x86_64/* ${WORKSPACE}
sudo docker rm -f $CID
popd
