#!/bin/sh
pushd ${WORKSPACE}
cp Dockerfile-autoconf Dockerfile
sudo docker build -t autoconf-env .
cat Dockerfile-ovs | envsubst | sudo docker build -t ovs -
CID=`sudo docker run -d ovs true`
sudo docker cp $CID:/root/rpmbuild/RPMS $PWD
sudo chmod -R a+w RPMS
mv RPMS/x86_64/* ${WORKSPACE}
sudo docker rm -f $CID
popd
