#!/bin/sh
pushd ${WORKSPACE}
cp Dockerfile-autoconf Dockerfile
sudo docker build -t autoconf .
container_with_env=`sudo docker run -d -e WORKSPACE=$WORKSPACE -e RELEASE=$BUILD_NUMBER -e PACKAGE_VERSION=$PACKAGE_VERSION -e HOME=/root autoconf`
sudo docker commit ${container_with_env} autoconf-env
cp Dockerfile-ovs Dockerfile
sudo docker build -t ovs .
CID=`sudo docker run -d ovs true`
sudo docker cp $CID:/root/rpmbuild/RPMS $PWD
sudo chmod -R a+w RPMS
mv RPMS/x86_64/* ${WORKSPACE}
sudo docker rm -f $CID
popd
